os: Visual Studio 2015

platform: x64

install:
    - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
    - appveyor-retry choco install strawberryperl --allow-empty-checksums
    - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
    - git clone https://github.com/tadzik/rakudobrew %USERPROFILE%\rakudobrew
    - SET PATH=%USERPROFILE%\rakudobrew\bin;%PATH%
    - rakudobrew build moar 2019.07.1
    - rakudobrew switch moar-2019.07.1
    - rakudobrew build-zef
    - cd %APPVEYOR_BUILD_FOLDER%
    - zef --depsonly install .

build: off

test_script:
    - zef test .

shallow_clone: true
