# An experimental AppVeyor config to install Strawberry Perl and
# Rakudo Star. Once installed, AppVeyor caches those for use next time.
#
# I specifically don't build Rakudo from GitHub because I want to use
# the "normal people" release.


# AppVeyor environment variables: https://www.appveyor.com/docs/environment-variables/

os: Visual Studio 2015

platform: x64

# clearing the cache: https://github.com/appveyor/ci/issues/985
# change .appveyor_clear_cache.txt to invalidate cache
#
# If the build is successful, AppVeyor caches these files and
# directories for future builds
cache:
    - C:\Strawberry -> .appveyor_clear_cache.txt
    - C:\Rakudo -> .appveyor_clear_cache.txt

branches:
    only:
        - master

# set your own environment variables here.
#
# Perl 5's Test::Harness has several env variables (many appear as prove switches)
#   https://metacpan.org/pod/Test::Harness

environment:
    MY_VAR: true
    MSIEXEC_WAIT_SECONDS: 100
    AUTOMATED_TESTING: 1
    TEST_VERBOSE: 0
    HARNESS_OPTIONS:
    HARNESS_VERBOSE: 0
    HARNESS_TIMER: 1
    HARNESS_PERL_SWITCHES: -MDevel::Cover

install:
    - if not exist "C:\rakudo" cinst rakudostar
    - SET PATH=C:\rakudo\bin;C:\rakudo\share\perl6\site\bin;%PATH%
    - ps: refreshenv
    - perl6 -v
    # install the target distribution's dependencies. You'll need to
    # maintain your META6.json file in the top-level directory
    - zef --verbose install .
    # change back to the target project's clone folder.
    # Now we should be ready to run the tests
    - cd %APPVEYOR_BUILD_FOLDER%

build: off

# many of the settings in `environment` affect what happens in the test script
#
# I'd like to run Devel::Cover and submit to Coveralls too.
test_script:
    - zef test .

shallow_clone: true

# Other Perl 6 AppVeyor configs
#   https://gist.github.com/ugexe/e95307a3a606df83fdcb
#   https://gist.github.com/MARTIMM/b0cc86cec30dbcabf6e9732a53879dbb/
#   https://github.com/perl6/atom-language-perl6/blob/master/appveyor.yml
#   https://github.com/azawawi/perl6-opencv/blob/master/appveyor.yml
#   https://github.com/ugexe/Perl6-Distribution--Common--Remote/blob/master/.appveyor.yml
#   https://github.com/azawawi/perl6-net-curl/blob/master/appveyor.yml
